### ISSUE TITLE
图片鉴赏功能会卡死bot

### ISSUE THREAD

**Issue by CYDXDianXian** [CYDXDianXian/AI_image_gen#18]
## 问题描述
@BlueDeer233 
- 使用图片鉴赏功能后，bot会毫异常卡死，不会留下任何报错记录。
- 在服务器端和本地端均会复现该bug，初步检查代码后暂未发现问题所在，故为了用户正常使用bot先暂时关闭了该功能

![image](https://user-images.githubusercontent.com/71607036/196492574-3d292a31-4dc0-4ff2-8dde-4a376b327d7b.png)

![image](https://user-images.githubusercontent.com/71607036/196492686-88fc08cf-6d3e-46f1-a19f-c3fefd57f0f0.png)

**Comment by BlueDeer233** [comment]
[尝试修复](https://github.com/CYDXDianXian/AI_image_gen/commit/1b5b1d1d7c2922725cacbdf484d47809d4390345)了一下，看看有没有效果

**Comment by CYDXDianXian** [comment]
哦，我的天，你先git pull一下再push，你把刚刚阿梓喵的更新又给删了。。。我这边先revert了

**Comment by BlueDeer233** [comment]
yeee，我pull过了。我去回滚一下，好像加了submodule我这得重新clone了  
得用这个指令克隆`git clone https://github.com/CYDXDianXian/AI_image_gen.git --recurse-submodules`

**Comment by CYDXDianXian** [comment]
还有我这边回复上传，回复图片鉴赏，和回复消息以图绘图都会报错，不知道是不是我的问题-.-
```
[2022-10-19 00:41:28,838 ai绘图] ERROR: <class 'TypeError'> occured when generate_tags handling message -476266195.
[2022-10-19 00:41:28,866 ai绘图] ERROR: string indices must be integers
Traceback (most recent call last):
  File "f:\python工程\Hoshinobot测试环境\HoshinoBot\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "f:\python工程\Hoshinobot测试环境\HoshinoBot\hoshino\modules\AI_image_gen\__init__.py", line 352, in generate_tags
    image, _, _ = await get_image_and_msg(bot, ev)
  File "f:\python工程\Hoshinobot测试环境\HoshinoBot\hoshino\modules\AI_image_gen\utils.py", line 66, in get_image_and_msg
    if i['type'] == 'image':
TypeError: string indices must be integers
```

**Comment by CYDXDianXian** [comment]
我这边有个更新，我先提交一下，以免冲突了

**Comment by BlueDeer233** [comment]
等下，我先回滚掉吧

**Comment by CYDXDianXian** [comment]
我已经回滚了

**Comment by BlueDeer233** [comment]
okok

**Comment by CYDXDianXian** [comment]
已经提交，你那边再拉取下更新吧

**Comment by CYDXDianXian** [comment]
目前测试已经正常，感谢蓝鹿酱~~
